Diploma/Controllers/FaceDetectionController.cs
using Diploma.Models;
using Diploma.Models.DataBase;
using Emgu.CV;
using Emgu.CV.Structure;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Diploma.Controllers
{

    public class FaceDetectionController : Controller
    {
        static readonly CascadeClassifier cascadeClassifier = new CascadeClassifier("C:/Users/Nameless/source/repos/Diploma/Diploma/Content/haarcascade_frontalface_alt_tree.xml");
        private DBContext db = new DBContext();

        
        // GET: FaceDetection
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Detect(HttpPostedFileBase uploadImage)
        {
            if (ModelState.IsValid && uploadImage != null)
            {
                Bitmap bitmap = new Bitmap(uploadImage.InputStream);

                Image<Bgr, byte> img = new Image<Bgr, byte>(bitmap);

                Rectangle[] rectangles = cascadeClassifier.DetectMultiScale(img, 1.1, 1);

                foreach (Rectangle rec in rectangles)
                {
                    using (Graphics gh = Graphics.FromImage(bitmap))
                    {
                        using (Pen pen = new Pen(Color.Red, 1))
                        {
                            gh.DrawRectangle(pen, rec);
                        }
                    }
                }

                var bitmapBytes = BitmapToBytes(bitmap); //Convert bitmap into a byte array
                return File(bitmapBytes, "image/jpeg"); //Return as file result
            }

            return RedirectToAction("Index");
        }

        private static byte[] BitmapToBytes(Bitmap img)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                img.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }
        }
    }
}

Diploma/Views/FaceDetection/Detect.cshtml
@{
    ViewBag.Title = "Detect";
}

<h2>Detect</h2>
@Html.Raw("<img src=\"" + @Url.Action("image") + "\" />")

Diploma/Views/FaceDetection/Index.cshtml
@{
    ViewBag.Title = "View";
}

<h2>Face detection</h2>

@using (Html.BeginForm("Detect", "FaceDetection", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <label>Upload image for detection</label>
    <div class="col-md-10">
        <input type="file" name="uploadImage" />
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Detect" class="btn btn-default" />
        </div>
    </div>
}